(function () {
  'use strict';

  var dict = {
    zh: {
      tagline: 'Chase the Zenith Light.',
      contactBtn: '联系我',
      navAbout: '关于我',
      navSkills: '经历与技能',
      navProjects: '项目',
      navBoard: '留言板',
      nextPage: '下一页',
      navTwin: '数字分身',
      agentTitle: '数字分身',
      agentIntro: '你可以问我关于我的问题',
      agentHello: '你好，我是何欣蔚的数字分身，问我点什么吧',
      agentFallback: '这个问题我还不太会，可以问我：你是谁 / 学校专业 / 特长 / 爱好 / 项目 / 联系方式',
      agentOffline: '我暂时答不上来，可以邮件联系我',
      agentLimit: '问得有点快，稍等一下再问我',
      chatPlaceholder: '问我点什么…',
      chatSend: '发送',
      agentDisclaimer: '回答由 AI 生成，仅供参考',
      qWho: '你是谁',
      qStudy: '学校和专业',
      qSkill: '你的特长',
      qHobby: '你的爱好',
      qContact: '怎么联系你',
      feedbackLink: '留言反馈',
      feedbackTitle: '反馈',
      feedbackIntro: '你的意见会帮我改进这个主页',
      feedbackRating: '评分（可选）',
      feedbackDevice: '使用设备',
      deviceDesktop: '电脑',
      deviceTablet: '平板',
      deviceMobile: '手机',
      deviceOther: '其他',
      feedbackText: '反馈内容',
      feedbackTextPlaceholder: '说说你的想法…',
      feedbackContact: '联系方式（可选）',
      feedbackSubmit: '提交',
      feedbackCancel: '取消',
      feedbackClose: '关闭',
      feedbackSoon: '反馈通道正在接入，敬请期待',
      feedbackEmpty: '请先填写内容',
      feedbackSending: '提交中…',
      feedbackSent: '已收到，谢谢你的反馈',
      feedbackError: '提交失败，请稍后再试',
      boardError: '留言加载失败',
      retry: '重试',
      aboutTitle: '关于我',
      aboutText1: '我是何欣蔚，天津大学智能医学工程专业本科生',
      aboutText2: '我喜欢探索新鲜事物，也喜欢音乐',
      aboutText3: '我偏爱小狗，偏爱那些毛茸茸、真诚而热烈的灵魂',
      skillsTitle: '经历与技能',
      eduLabel: '教育背景',
      eduText: '天津大学 · 智能医学工程 · 本科在读',
      interestLabel: '兴趣与特长',
      tagErhu: '二胡',
      tagSeal: '篆刻',
      projectsTitle: '项目',
      projectsText: '项目案例正在整理中，将陆续分享课程项目与设计探索',
      contactTitle: '联系我',
      contactHint: '欢迎联系我',
      emailLabel: '邮箱：',
      sendEmailBtn: '发送邮件',
      boardTitle: '留言板',
      nickLabel: '昵称',
      msgLabel: '留言',
      msgPlaceholder: '写点什么…',
      anonLabel: '匿名',
      msgColorLabel: '气泡颜色',
      colorCoral: '珊瑚红',
      colorAmber: '暖橙',
      colorSky: '天蓝',
      colorMint: '薄荷绿',
      colorLilac: '淡紫',
      relLabel: '与我的关系',
      relClassmate: '同学',
      relFriend: '朋友',
      relFamily: '家人',
      relTeacher: '老师',
      relOther: '其他',
      adminOpen: '管理',
      adminTitle: '管理员登录',
      adminIntro: '只有管理员可以隐藏或清空留言',
      adminEmail: '邮箱',
      adminPass: '密码',
      adminLogin: '登录',
      adminClear: '清空留言板',
      adminSignOut: '退出管理',
      adminHide: '隐藏',
      adminAuthFail: '登录失败，请检查邮箱和密码',
      adminSignedIn: '已进入管理模式',
      adminClearConfirm: '确定清空所有留言吗？',
      sendBtn: '发送',
      clearBtn: '清空留言',
      anonymousName: '匿名',
      emptyMsg: '还没有留言',
      msgSending: '发送中...',
      msgSent: '已发送，谢谢你的留言',
      msgError: '发送失败，请重试',
      msgEmpty: '请先填写留言',
      themeLabel: '主题',
      themeSystem: '跟随系统',
      themeLight: '浅色模式',
      themeDark: '深色模式',
      footerNote: '反馈与留言会发送到 Supabase，仅用于改进这个主页'
    },
    en: {
      tagline: 'Chase the Zenith Light.',
      contactBtn: 'Contact Me',
      navAbout: 'About',
      navSkills: 'Skills',
      navProjects: 'Projects',
      navBoard: 'Message Board',
      nextPage: 'Next',
      navTwin: 'Digital Twin',
      agentTitle: 'Digital Twin',
      agentIntro: 'You can ask me about myself',
      agentHello: 'Hi, I am the digital twin of He Xinwei. Ask me anything',
      agentFallback: 'I am not sure about that yet. You can ask: who are you / school / skills / hobbies / projects / contact',
      agentOffline: 'I cannot answer that right now, feel free to email me',
      agentLimit: 'A bit too fast, please ask again in a moment',
      chatPlaceholder: 'Ask me something...',
      chatSend: 'Send',
      agentDisclaimer: 'Answers are generated by AI, for reference only',
      qWho: 'Who are you',
      qStudy: 'School and major',
      qSkill: 'Your skills',
      qHobby: 'Your hobbies',
      qContact: 'How to contact you',
      feedbackLink: 'Feedback',
      feedbackTitle: 'Feedback',
      feedbackIntro: 'Your feedback helps me improve this page',
      feedbackRating: 'Rating (optional)',
      feedbackDevice: 'Your device',
      deviceDesktop: 'Desktop',
      deviceTablet: 'Tablet',
      deviceMobile: 'Mobile',
      deviceOther: 'Other',
      feedbackText: 'Your feedback',
      feedbackTextPlaceholder: 'Tell me what you think...',
      feedbackContact: 'Contact (optional)',
      feedbackSubmit: 'Submit',
      feedbackCancel: 'Cancel',
      feedbackClose: 'Close',
      feedbackSoon: 'The feedback channel is coming soon',
      feedbackEmpty: 'Please fill in your feedback first',
      feedbackSending: 'Sending...',
      feedbackSent: 'Thank you for your feedback',
      feedbackError: 'Submit failed, please try again later',
      boardError: 'Could not load messages',
      retry: 'Retry',
      aboutTitle: 'About Me',
      aboutText1: 'I am He Xinwei, an undergraduate in Intelligent Medical Engineering at Tianjin University',
      aboutText2: 'I like exploring new things and I love music',
      aboutText3: 'I have a special fondness for dogs, for those furry souls so sincere and full of warmth.',
      skillsTitle: 'Experience & Skills',
      eduLabel: 'Education',
      eduText: 'Tianjin University · Intelligent Medical Engineering · Undergraduate',
      interestLabel: 'Interests & Skills',
      tagErhu: 'Erhu',
      tagSeal: 'Seal carving',
      projectsTitle: 'Projects',
      projectsText: 'Project cases are being organized. Course projects and design explorations will be shared soon',
      contactTitle: 'Contact Me',
      contactHint: 'Feel free to contact me',
      emailLabel: 'Email: ',
      sendEmailBtn: 'Send Email',
      boardTitle: 'Message Board',
      nickLabel: 'Nickname',
      msgLabel: 'Message',
      msgPlaceholder: 'Write something...',
      anonLabel: 'Anonymous',
      msgColorLabel: 'Bubble color',
      colorCoral: 'Coral',
      colorAmber: 'Amber',
      colorSky: 'Sky blue',
      colorMint: 'Mint',
      colorLilac: 'Lilac',
      relLabel: 'Relation to me',
      relClassmate: 'Classmate',
      relFriend: 'Friend',
      relFamily: 'Family',
      relTeacher: 'Teacher',
      relOther: 'Other',
      adminOpen: 'Admin',
      adminTitle: 'Admin sign in',
      adminIntro: 'Only the admin can hide or clear messages',
      adminEmail: 'Email',
      adminPass: 'Password',
      adminLogin: 'Sign in',
      adminClear: 'Clear all messages',
      adminSignOut: 'Sign out',
      adminHide: 'Hide',
      adminAuthFail: 'Sign in failed. Check email and password',
      adminSignedIn: 'Admin mode on',
      adminClearConfirm: 'Clear all messages?',
      sendBtn: 'Send',
      clearBtn: 'Clear messages',
      anonymousName: 'Anonymous',
      emptyMsg: 'No messages yet',
      msgSending: 'Sending...',
      msgSent: 'Sent. Thank you for your message',
      msgError: 'Failed to send. Please try again',
      msgEmpty: 'Please write a message first',
      themeLabel: 'Theme',
      themeSystem: 'System',
      themeLight: 'Light',
      themeDark: 'Dark',
      footerNote: 'Feedback and messages are sent to Supabase and used only to improve this page'
    }
  };

  var relKeys = {
    classmate: 'relClassmate',
    friend: 'relFriend',
    family: 'relFamily',
    teacher: 'relTeacher',
    other: 'relOther'
  };
  var STORE_KEY = 'site_messages';
  var THEME_KEY = 'theme';
  var LIGHT_KEY = 'lang';
  var current = 'zh';
  var themeMode = 'system';
  var themeMenuOpen = false;
  var reduceMotion = !!(window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches);

  var SUPABASE_URL = 'https://nntyiphwrxwxffiqwqle.supabase.co';
  var SUPABASE_KEY = 'sb_publishable_D6bM1TurtNQgilXkBbZdbg_ldDxZzSW';

  var adminToken = null;
  var ADMIN_KEY = 'admin_token';
  try { adminToken = sessionStorage.getItem(ADMIN_KEY); } catch (e) { adminToken = null; }

  function updateAdminUI() {
    var bar = document.getElementById('adminBar');
    if (!bar) { return; }
    if (adminToken) { bar.removeAttribute('hidden'); }
    else { bar.setAttribute('hidden', ''); }
  }

  function adminSignIn(email, password) {
    return fetch(SUPABASE_URL + '/auth/v1/token?grant_type=password', {
      method: 'POST',
      headers: { apikey: SUPABASE_KEY, 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: email, password: password })
    }).then(function (res) {
      if (!res.ok) { throw new Error('auth'); }
      return res.json();
    }).then(function (data) {
      adminToken = data.access_token;
      try { sessionStorage.setItem(ADMIN_KEY, adminToken); } catch (e) {}
      updateAdminUI();
      return true;
    });
  }

  function adminSignOut() {
    adminToken = null;
    try { sessionStorage.removeItem(ADMIN_KEY); } catch (e) {}
    updateAdminUI();
    return renderBoard();
  }

  function hideMessage(id) {
    return apiFetch('messages?id=eq.' + encodeURIComponent(id), {
      method: 'PATCH',
      prefer: 'return=minimal',
      body: { is_visible: false }
    }).then(function () { return renderBoard(); });
  }

  function clearAllMessages() {
    return apiFetch('messages?id=not.is.null', {
      method: 'DELETE',
      prefer: 'return=minimal'
    }).then(function () { return renderBoard(); });
  }

  function initAdmin() {
    var modal = document.getElementById('adminModal');
    var openBtn = document.getElementById('adminOpen');
    var closeBtn = document.getElementById('adminClose');
    var cancelBtn = document.getElementById('adminCancel');
    var form = document.getElementById('adminForm');
    var email = document.getElementById('adminEmail');
    var pass = document.getElementById('adminPass');
    var clearBtn = document.getElementById('adminClear');
    var outBtn = document.getElementById('adminSignOut');
    var list = document.getElementById('msgList');
    if (!modal || !openBtn) { return; }

    updateAdminUI();

    var openModal = function () { modal.removeAttribute('hidden'); if (email) { email.focus(); } };
    var closeModal = function () { modal.setAttribute('hidden', ''); };

    openBtn.addEventListener('click', openModal);
    if (closeBtn) { closeBtn.addEventListener('click', closeModal); }
    if (cancelBtn) { cancelBtn.addEventListener('click', closeModal); }
    modal.addEventListener('click', function (e) {
      if (e.target && e.target.getAttribute && e.target.getAttribute('data-admin-close')) { closeModal(); }
    });

    if (form) {
      form.addEventListener('submit', function (e) {
        e.preventDefault();
        var em = email ? email.value.trim() : '';
        var pw = pass ? pass.value : '';
        if (!em || !pw) { showToast(t('adminAuthFail'), 'error'); return; }
        adminSignIn(em, pw).then(function () {
          if (pass) { pass.value = ''; }
          closeModal();
          showToast(t('adminSignedIn'), 'success');
          return renderBoard();
        }).catch(function () {
          showToast(t('adminAuthFail'), 'error');
        });
      });
    }

    if (outBtn) { outBtn.addEventListener('click', function () { adminSignOut(); }); }

    if (clearBtn) {
      clearBtn.addEventListener('click', function () {
        if (!adminToken) { return; }
        if (!window.confirm(t('adminClearConfirm'))) { return; }
        clearAllMessages().catch(function () { showToast(t('msgError'), 'error'); });
      });
    }

    if (list) {
      list.addEventListener('click', function (e) {
        var btn = e.target.closest ? e.target.closest('.msg-admin') : null;
        if (!btn || !adminToken) { return; }
        hideMessage(btn.getAttribute('data-id')).catch(function () { showToast(t('msgError'), 'error'); });
      });
    }
  }
  function apiFetch(path, options) {
    var opts = options || {};
    var headers = {
      apikey: SUPABASE_KEY,
      Authorization: 'Bearer ' + (adminToken || SUPABASE_KEY),
      'Content-Type': 'application/json'
    };
    if (opts.prefer) { headers.Prefer = opts.prefer; }
    return fetch(SUPABASE_URL + '/rest/v1/' + path, {
      method: opts.method || 'GET',
      headers: headers,
      body: opts.body ? JSON.stringify(opts.body) : undefined
    }).then(function (res) {
      if (!res.ok) {
        return res.text().then(function (txt) {
          throw new Error('HTTP ' + res.status + ' ' + txt);
        });
      }
      var ct = res.headers.get('content-type') || '';
      if (ct.indexOf('application/json') > -1) { return res.json(); }
      return true;
    });
  }

  function deviceLabel() {
    var ua = navigator.userAgent || '';
    var os = /Windows/i.test(ua) ? 'Windows'
      : /Macintosh|Mac OS X/i.test(ua) ? 'macOS'
      : /Android/i.test(ua) ? 'Android'
      : /iPhone|iPad|iPod/i.test(ua) ? 'iOS'
      : /Linux/i.test(ua) ? 'Linux' : '其他';
    var br = /Edg\//i.test(ua) ? 'Edge'
      : /Chrome\//i.test(ua) ? 'Chrome'
      : /Firefox\//i.test(ua) ? 'Firefox'
      : /Safari\//i.test(ua) ? 'Safari' : '浏览器';
    return os + ' · ' + br;
  }

  function getSavedLang() {
    try { return localStorage.getItem(LIGHT_KEY); } catch (e) { return null; }
  }
  function saveLang(lang) {
    try { localStorage.setItem(LIGHT_KEY, lang); } catch (e) {}
  }
  function detectLang() {
    var saved = getSavedLang();
    if (saved === 'zh' || saved === 'en') { return saved; }
    var nav = (navigator.language || navigator.userLanguage || 'zh').toLowerCase();
    return nav.indexOf('zh') === 0 ? 'zh' : 'en';
  }
  function t(key) {
    return dict[current][key] || key;
  }
  function getSavedTheme() {
    try {
      var v = localStorage.getItem(THEME_KEY);
      return (v === 'light' || v === 'dark' || v === 'system') ? v : 'system';
    } catch (e) { return 'system'; }
  }
  function saveTheme(mode) {
    try { localStorage.setItem(THEME_KEY, mode); } catch (e) {}
  }
  function systemDark() {
    return !!(window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches);
  }
  function applyTheme(mode) {
    themeMode = mode;
    var dark = mode === 'dark' || (mode === 'system' && systemDark());
    var root = document.documentElement;
    root.setAttribute('data-theme', dark ? 'dark' : 'light');
    root.setAttribute('data-theme-mode', mode);
    var opts = document.querySelectorAll('.theme-menu li');
    for (var i = 0; i < opts.length; i++) {
      var on = opts[i].getAttribute('data-theme-mode') === mode;
      opts[i].classList.toggle('is-active', on);
      opts[i].setAttribute('aria-selected', on ? 'true' : 'false');
    }
  }
  function setThemeMenu(open) {
    var menu = document.getElementById('themeMenu');
    var btn = document.getElementById('themeToggle');
    if (!menu || !btn) { return; }
    themeMenuOpen = open;
    if (open) { menu.removeAttribute('hidden'); } else { menu.setAttribute('hidden', ''); }
    btn.setAttribute('aria-expanded', open ? 'true' : 'false');
    if (open) {
      var target = menu.querySelector('li.is-active') || menu.querySelector('li');
      if (target) { target.focus(); }
    }
  }
  function initTheme() {
    var btn = document.getElementById('themeToggle');
    var menu = document.getElementById('themeMenu');
    applyTheme(getSavedTheme());
    if (!btn || !menu) { return; }
    var opts = menu.querySelectorAll('li');
    btn.addEventListener('click', function (e) {
      if (e) { e.stopPropagation(); }
      setThemeMenu(!themeMenuOpen);
    });
    btn.addEventListener('keydown', function (e) {
      if (e.key === 'ArrowDown') { e.preventDefault(); setThemeMenu(true); }
      else if (e.key === 'Escape') { setThemeMenu(false); }
    });
    for (var i = 0; i < opts.length; i++) {
      opts[i].addEventListener('click', function () {
        var mode = this.getAttribute('data-theme-mode');
        saveTheme(mode);
        applyTheme(mode);
        setThemeMenu(false);
        btn.focus();
      });
      opts[i].addEventListener('keydown', function (e) {
        var list = Array.prototype.slice.call(opts);
        var idx = list.indexOf(this);
        if (e.key === 'ArrowDown') {
          e.preventDefault();
          list[(idx + 1) % list.length].focus();
        } else if (e.key === 'ArrowUp') {
          e.preventDefault();
          list[(idx - 1 + list.length) % list.length].focus();
        } else if (e.key === 'Enter' || e.key === ' ' || e.key === 'Spacebar') {
          e.preventDefault();
          this.click();
        } else if (e.key === 'Escape') {
          e.preventDefault();
          setThemeMenu(false);
          btn.focus();
        }
      });
    }
    document.addEventListener('click', function (e) {
      if (!themeMenuOpen) { return; }
      if (e.target.closest && e.target.closest('.theme')) { return; }
      setThemeMenu(false);
    });
    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape' && themeMenuOpen) { setThemeMenu(false); btn.focus(); }
    });
    if (window.matchMedia) {
      var mq = window.matchMedia('(prefers-color-scheme: dark)');
      var onChange = function () { if (themeMode === 'system') { applyTheme('system'); } };
      if (mq.addEventListener) { mq.addEventListener('change', onChange); }
      else if (mq.addListener) { mq.addListener(onChange); }
    }
  }
  function loadMessages() {
    return apiFetch('messages?select=*&is_visible=eq.true&order=created_at.desc&limit=50');
  }
  function sendMessage(data) {
    return apiFetch('messages', { method: 'POST', prefer: 'return=minimal', body: data });
  }
  function layoutBoard() {
    var ul = document.getElementById('msgList');
    if (!ul) { return; }
    var items = ul.querySelectorAll('.msg-item');
    if (!items.length) { return; }
    if (ul.offsetHeight === 0) { return; }
    var isDesk = !!(window.matchMedia && window.matchMedia('(min-width: 640px)').matches);
    var isWide = !!(window.matchMedia && window.matchMedia('(min-width: 900px)').matches);
    var cols = isWide ? 3 : (isDesk ? 2 : 1);
    var rowH = 1;
    for (var i = 0; i < items.length; i++) {
      var el = items[i];
      el.style.gridRowEnd = '';
      el.style.gridColumn = '';
      el.classList.remove('msg-w-sm', 'msg-w-md', 'msg-w-lg', 'msg-right');
      var len = parseInt(el.getAttribute('data-len') || '0', 10);
      if (!isDesk) {
        if (len <= 12) { el.classList.add('msg-w-sm'); }
        else if (len <= 40) { el.classList.add('msg-w-md'); }
        else { el.classList.add('msg-w-lg'); }
        if (i % 2 === 1) { el.classList.add('msg-right'); }
        continue;
      }
      if (cols > 1 && el.getAttribute('data-wide') === '1') {
        el.style.gridColumn = 'span 2';
      }
      var h = el.offsetHeight;
      var rows = Math.max(1, Math.ceil(h / rowH));
      el.style.gridRowEnd = 'span ' + rows;
    }
  }

  function initBoardLayout() {
    var timer = null;
    window.addEventListener('resize', function () {
      if (timer) { window.clearTimeout(timer); }
      timer = window.setTimeout(function () { timer = null; layoutBoard(); }, 150);
    });
    if (document.fonts && document.fonts.ready && document.fonts.ready.then) {
      document.fonts.ready.then(function () { layoutBoard(); });
    }
  }
  function renderBoard() {
    var ul = document.getElementById('msgList');
    if (!ul) { return; }
    return loadMessages().then(function (list) {
      ul.textContent = '';
      if (!list || list.length === 0) {
        var empty = document.createElement('li');
        empty.className = 'msg-empty';
        empty.textContent = t('emptyMsg');
        ul.appendChild(empty);
        return;
      }
      var palette = ['coral', 'amber', 'sky', 'mint', 'lilac'];
      for (var i = 0; i < list.length; i++) {
        var m = list[i];
        var li = document.createElement('li');
        var tone = palette.indexOf(m.color) > -1 ? m.color : 'coral';
        li.className = 'msg-item color-' + tone;
        var rawText = String(m.content || '');
        li.setAttribute('data-len', String(rawText.length));
        var idStr = String(m.id || '');
        var hash = 0;
        for (var hi = 0; hi < idStr.length; hi++) { hash = (hash * 31 + idStr.charCodeAt(hi)) % 997; }
        li.setAttribute('data-wide', (hash % 3 === 0) ? '1' : '0');
        var head = document.createElement('div');
        head.className = 'msg-head';
        var name = document.createElement('span');
        name.className = 'msg-name';
        name.textContent = (m.nickname && String(m.nickname).trim()) ? String(m.nickname).trim() : t('anonymousName');
        var time = document.createElement('time');
        time.className = 'msg-time';
        time.textContent = (m.created_at ? new Date(m.created_at) : new Date()).toLocaleString();
        head.appendChild(name);
        if (m.relation && relKeys[m.relation]) {
          var relTag = document.createElement('span');
          relTag.className = 'msg-rel-tag';
          relTag.textContent = t(relKeys[m.relation]);
          head.appendChild(relTag);
        }
        head.appendChild(time);
        if (adminToken && m.id) {
          var hideBtn = document.createElement('button');
          hideBtn.type = 'button';
          hideBtn.className = 'msg-admin';
          hideBtn.setAttribute('data-id', m.id);
          hideBtn.textContent = t('adminHide');
          head.appendChild(hideBtn);
        }
        var body = document.createElement('p');
        body.className = 'msg-body';
        body.textContent = String(m.content || '');
        li.appendChild(head);
        li.appendChild(body);
        ul.appendChild(li);
      }
      layoutBoard();
    }).catch(function () {
      ul.textContent = '';
      var err = document.createElement('li');
      err.className = 'msg-empty';
      err.textContent = t('boardError') + ' ';
      var retryBtn = document.createElement('button');
      retryBtn.type = 'button';
      retryBtn.className = 'clear-btn';
      retryBtn.textContent = t('retry');
      retryBtn.addEventListener('click', function () { renderBoard(); });
      err.appendChild(retryBtn);
      ul.appendChild(err);
    });
  }
  function showToast(message, type) {
    var wrap = document.querySelector('.toast-wrap');
    if (!wrap) {
      wrap = document.createElement('div');
      wrap.className = 'toast-wrap';
      document.body.appendChild(wrap);
    }
    var toast = document.createElement('div');
    var isError = type === 'error';
    toast.className = 'toast ' + (isError ? 'toast-error' : 'toast-success');
    toast.setAttribute('role', 'status');
    if (isError) {
      var icon = document.createElement('span');
      icon.className = 'toast-icon';
      icon.setAttribute('aria-hidden', 'true');
      icon.textContent = '!';
      toast.appendChild(icon);
    }
    var textNode = document.createElement('span');
    textNode.className = 'toast-text';
    textNode.textContent = message;
    toast.appendChild(textNode);
    wrap.appendChild(toast);
    window.requestAnimationFrame(function () { toast.classList.add('show'); });
    window.setTimeout(function () {
      toast.classList.remove('show');
      window.setTimeout(function () { toast.remove(); }, 240);
    }, 2200);
  }
  function addRipple(btn, x, y) {
    if (reduceMotion) { return; }
    var rect = btn.getBoundingClientRect();
    var size = Math.max(rect.width, rect.height) * 1.2;
    var ripple = document.createElement('span');
    ripple.className = 'ripple';
    ripple.style.width = size + 'px';
    ripple.style.height = size + 'px';
    ripple.style.left = (x - rect.left - size / 2) + 'px';
    ripple.style.top = (y - rect.top - size / 2) + 'px';
    btn.appendChild(ripple);
    window.setTimeout(function () { ripple.remove(); }, 280);
  }
  function applyLang(lang) {
    current = lang;
    document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en';
    document.title = lang === 'zh' ? '何欣蔚 | 个人主页' : 'He Xinwei | Homepage';
    var nodes = document.querySelectorAll('[data-i18n]');
    for (var i = 0; i < nodes.length; i++) {
      var key = nodes[i].getAttribute('data-i18n');
      if (dict[lang][key]) { nodes[i].textContent = dict[lang][key]; }
    }
    var ph = document.querySelectorAll('[data-i18n-placeholder]');
    for (var j = 0; j < ph.length; j++) {
      var k = ph[j].getAttribute('data-i18n-placeholder');
      if (dict[lang][k]) { ph[j].setAttribute('placeholder', dict[lang][k]); }
    }
    var ariaNodes = document.querySelectorAll('[data-i18n-aria]');
    for (var m = 0; m < ariaNodes.length; m++) {
      var ak = ariaNodes[m].getAttribute('data-i18n-aria');
      if (dict[lang][ak]) { ariaNodes[m].setAttribute('aria-label', dict[lang][ak]); }
    }
    var btn = document.getElementById('langToggle');
    if (btn) {
      btn.textContent = lang === 'zh' ? 'EN' : '中文';
      btn.setAttribute('aria-label', lang === 'zh' ? 'Switch to English' : 'Switch to Chinese');
    }
    renderBoard();
    if (agentGreeting) { agentGreeting.textContent = dict[lang].agentHello; }
  }
  function initBoard() {
    var form = document.getElementById('msgForm');
    var anonBox = document.getElementById('msgAnon');
    var nickInput = document.getElementById('msgNick');
    var colorRow = document.getElementById('colorRow');
    var msgColor = 'coral';
    var more = document.getElementById('msgMore');
    var relRow = document.getElementById('relRow');
    var textInput = document.getElementById('msgText');
    var msgRel = '';

    if (anonBox && nickInput) {
      anonBox.addEventListener('change', function () { nickInput.disabled = anonBox.checked; });
    }

    var openMore = function () {
      if (!more || !more.hidden) { return; }
      more.hidden = false;
      more.classList.add('is-open');
      window.setTimeout(function () { more.classList.remove('is-open'); }, 300);
    };
    if (textInput) {
      textInput.addEventListener('focus', openMore);
      textInput.addEventListener('input', openMore);
      textInput.addEventListener('blur', function () {
        window.setTimeout(function () {
          if (!more) { return; }
          var active = document.activeElement;
          if (active && more.contains(active)) { return; }
          if (textInput.value.trim() === '') { more.hidden = true; }
        }, 160);
      });
    }
    if (relRow) {
      relRow.addEventListener('click', function (e) {
        var chip = e.target.closest ? e.target.closest('.rel-chip') : null;
        if (!chip) { return; }
        var value = chip.getAttribute('data-rel') || '';
        msgRel = (msgRel === value) ? '' : value;
        var chips = relRow.querySelectorAll('.rel-chip');
        for (var i = 0; i < chips.length; i++) {
          chips[i].classList.toggle('is-on', chips[i].getAttribute('data-rel') === msgRel);
        }
      });
    }
    if (colorRow) {
      colorRow.addEventListener('click', function (e) {
        var dot = e.target.closest ? e.target.closest('.color-dot') : null;
        if (!dot) { return; }
        msgColor = dot.getAttribute('data-color') || 'coral';
        var dots = colorRow.querySelectorAll('.color-dot');
        for (var i = 0; i < dots.length; i++) {
          dots[i].setAttribute('aria-pressed', dots[i] === dot ? 'true' : 'false');
        }
      });
    }

    if (form) {
      form.addEventListener('submit', function (e) {
        e.preventDefault();
        var submitBtn = form.querySelector('button[type="submit"]');
        var nick = (anonBox && anonBox.checked) ? '' : (nickInput ? nickInput.value.trim() : '');
        var textArea = document.getElementById('msgText');
        var text = textArea ? textArea.value.trim() : '';
        if (!text) { showToast(t('msgEmpty'), 'error'); return; }
        if (submitBtn) { submitBtn.disabled = true; submitBtn.textContent = t('msgSending'); }
        sendMessage({ nickname: nick, content: text, color: msgColor, relation: msgRel }).catch(function (err) {
          var emsg = String((err && err.message) || '');
          if (emsg.indexOf('color') > -1 || emsg.indexOf('relation') > -1) {
            return sendMessage({ nickname: nick, content: text });
          }
          throw err;
        }).then(function () {
          form.reset();
          msgRel = '';
          if (relRow) {
            var relChips = relRow.querySelectorAll('.rel-chip');
            for (var rc = 0; rc < relChips.length; rc++) { relChips[rc].classList.remove('is-on'); }
          }
          if (more) { more.hidden = true; }
          if (anonBox && nickInput) { nickInput.disabled = anonBox.checked; }
          return renderBoard();
        }).then(function () {
          showToast(t('msgSent'), 'success');
        }).catch(function () {
          showToast(t('msgError'), 'error');
        }).then(function () {
          if (submitBtn) { submitBtn.disabled = false; submitBtn.textContent = t('sendBtn'); }
        });
      });
    }
  }
  function initPointerEffects() {
    var finePointer = !!(window.matchMedia && window.matchMedia('(hover: hover) and (pointer: fine)').matches);
    if (!finePointer || reduceMotion) { return; }

    var glow = document.createElement('div');
    glow.className = 'hero-glow';
    glow.setAttribute('aria-hidden', 'true');
    document.body.insertBefore(glow, document.body.firstChild);

    var glowX = 0;
    var glowY = 0;
    var glowRaf = null;
    var drawGlow = function () {
      glowRaf = null;
      glow.style.transform = 'translate(' + glowX + 'px,' + glowY + 'px) translate(-50%,-50%)';
    };

    document.addEventListener('pointermove', function (e) {
      if (e.pointerType === 'touch') { return; }
      glowX = e.clientX;
      glowY = e.clientY;
      glow.classList.add('is-on');
      if (glowRaf === null) { glowRaf = window.requestAnimationFrame(drawGlow); }
    });
    document.addEventListener('pointerleave', function () { glow.classList.remove('is-on'); });
    window.addEventListener('blur', function () { glow.classList.remove('is-on'); });

    var MAX_TILT = 3;
    var PERSPECTIVE = 1100;
    var EASE = 0.12;
    var cards = document.querySelectorAll('.card:not(.agent)');

    var bindCard = function (card) {
      var targetX = 0;
      var targetY = 0;
      var currentX = 0;
      var currentY = 0;
      var rafId = null;
      var hovering = false;

      var draw = function () {
        currentX += (targetX - currentX) * EASE;
        currentY += (targetY - currentY) * EASE;
        var settled = Math.abs(targetX - currentX) < 0.01 && Math.abs(targetY - currentY) < 0.01;
        if (settled) { currentX = targetX; currentY = targetY; }
        if (!hovering && Math.abs(currentX) < 0.01 && Math.abs(currentY) < 0.01) {
          card.style.transform = '';
          card.classList.remove('is-tilting');
          rafId = null;
          return;
        }
        card.style.transform = 'perspective(' + PERSPECTIVE + 'px) rotateX(' + currentX.toFixed(3) + 'deg) rotateY(' + currentY.toFixed(3) + 'deg)';
        if (settled) { rafId = null; return; }
        rafId = window.requestAnimationFrame(draw);
      };

      var start = function () {
        if (rafId === null) { rafId = window.requestAnimationFrame(draw); }
      };

      card.classList.add('is-tiltable');
      card.addEventListener('pointerenter', function () { hovering = true; card.classList.add('is-tilting'); start(); });
      card.addEventListener('pointermove', function (e) {
        var rect = card.getBoundingClientRect();
        var px = (e.clientX - rect.left) / rect.width - 0.5;
        var py = (e.clientY - rect.top) / rect.height - 0.5;
        targetY = px * MAX_TILT * 2;
        targetX = -py * MAX_TILT * 2;
        hovering = true;
        start();
      });
      card.addEventListener('pointerleave', function () { hovering = false; targetX = 0; targetY = 0; start(); });
    };

    for (var i = 0; i < cards.length; i++) { bindCard(cards[i]); }
  }
  function initPager() {
    var ids = ['page1', 'page2', 'page3', 'page4'];
    var pages = [];
    for (var p = 0; p < ids.length; p++) {
      var el = document.getElementById(ids[p]);
      if (el) { pages.push(el); }
    }
    if (pages.length < 2) { return null; }

    var arrows = document.querySelectorAll('.page-next');
    var motionOK = !reduceMotion && document.documentElement.classList.contains('js-motion');

    document.documentElement.setAttribute('data-page', pages[0].id);
    window.scrollTo(0, 0);

    var indexOfId = function (id) {
      for (var i = 0; i < pages.length; i++) {
        if (pages[i].id === id) { return i; }
      }
      return -1;
    };

    if (!motionOK) {
      for (var a = 0; a < arrows.length; a++) {
        (function (arrow) {
          arrow.addEventListener('click', function () {
            var t = indexOfId(arrow.getAttribute('data-target'));
            if (t > -1) { pages[t].scrollIntoView(); }
          });
        })(arrows[a]);
      }
      var heroArrow = document.getElementById('nextPage');
      if (heroArrow) {
        heroArrow.addEventListener('click', function () {
          var to2 = indexOfId('page2');
          if (to2 > -1) { pages[to2].scrollIntoView(); }
        });
      }
      return null;
    }

    var idx = 0;
    var memo = {};
    var animating = false;
    var isMobile = !!(window.matchMedia && window.matchMedia('(max-width: 640px)').matches);
    var leadDelay = isMobile ? 80 : 140;
    var leadTime = isMobile ? 360 : 560;
    var unlockTime = isMobile ? 560 : 820;
    var touchSlack = isMobile ? 70 : 4;

    var setArrow = function (i) {
      var nextId = pages[i + 1] ? pages[i + 1].id : '';
      for (var a2 = 0; a2 < arrows.length; a2++) {
        var on = nextId !== '' && arrows[a2].getAttribute('data-target') === nextId;
        arrows[a2].classList.toggle('is-active', on);
      }
    };

    var swap = function (to) {
      if (animating || to < 0 || to >= pages.length || to === idx) { return; }
      animating = true;
      memo[idx] = window.pageYOffset;
      var from = pages[idx];
      var target = pages[to];

      var finish = function () {
        if (from) { from.classList.remove('is-active', 'is-entered', 'is-leaving', 'is-leaving-down', 'is-armed', 'is-armed-down', 'is-up'); }
        target.classList.add('is-active');
        if (target.id === 'page3') {
          layoutBoard();
          window.setTimeout(layoutBoard, 700);
        }
        var allArrows = document.querySelectorAll('.page-next');
        for (var ai = 0; ai < allArrows.length; ai++) { allArrows[ai].classList.remove('is-pulling'); }
        setArrow(to);
        var newArrow = document.querySelector('.page-next.is-active');
        if (newArrow) {
          newArrow.classList.add('is-arriving');
          window.requestAnimationFrame(function () {
            window.requestAnimationFrame(function () { newArrow.classList.remove('is-arriving'); });
          });
        }
        document.documentElement.setAttribute('data-page', target.id);
        var footer = document.querySelector('footer');
        var safeMax = footer ? Math.max(0, footer.offsetTop - window.innerHeight) : 0;
        var activeArrow = document.querySelector('.page-next.is-active');
        if (activeArrow) { safeMax = Math.min(safeMax, Math.max(0, activeArrow.offsetTop - window.innerHeight)); }
        var targetPos = to === 0 ? 0 : (memo[to] || 0);
        window.scrollTo(0, Math.min(targetPos, safeMax));
        window.requestAnimationFrame(function () {
          window.requestAnimationFrame(function () {
            target.classList.add('is-entered');
            window.setTimeout(function () { animating = false; }, unlockTime);
          });
        });
        idx = to;
      };

      if (from) {
        var down = to > idx;
        target.classList.toggle('is-up', !down);
        var oldArrow = document.querySelector('.page-next.is-active');
        if (oldArrow) { oldArrow.classList.add('is-pulling'); }
        from.classList.add(down ? 'is-armed' : 'is-armed-down');
        window.setTimeout(function () { from.classList.add(down ? 'is-leaving' : 'is-leaving-down'); }, leadDelay);
        window.setTimeout(finish, leadTime);
      } else {
        finish();
      }
    };

    for (var a3 = 0; a3 < arrows.length; a3++) {
      (function (arrow) {
        arrow.addEventListener('click', function () {
          swap(indexOfId(arrow.getAttribute('data-target')));
        });
      })(arrows[a3]);
    }

    var heroArrow2 = document.getElementById('nextPage');
    if (heroArrow2) {
      heroArrow2.addEventListener('click', function () { swap(indexOfId('page2')); });
    }

    setArrow(0);

    var navLinks = document.querySelectorAll('.nav a[href^="#"], .brand[href^="#"]');
    for (var n = 0; n < navLinks.length; n++) {
      navLinks[n].addEventListener('click', function (e) {
        var href = this.getAttribute('href');
        if (!href || href.length < 2) { return; }
        if (href === '#top' || href === '#page1') {
          if (idx !== 0) { e.preventDefault(); swap(0); }
          return;
        }
        var target = document.querySelector(href);
        if (!target) { return; }
        for (var t = 0; t < pages.length; t++) {
          if (pages[t].contains(target)) {
            if (t !== idx) {
              e.preventDefault();
              memo[t] = 0;
              swap(t);
              window.setTimeout(function () { target.scrollIntoView({ behavior: 'smooth', block: 'start' }); }, 760);
            }
            return;
          }
        }
      });
    }

    var wheelAccum = 0;
    var wheelAt = 0;

    window.addEventListener('wheel', function (e) {
      if (e.ctrlKey || animating || document.documentElement.classList.contains('feedback-open')) { return; }
      var node = e.target;
      if (node && node.closest && node.closest('.chat-log')) { return; }
      var atTop = window.pageYOffset <= 4;
      var atBottom = (window.innerHeight + window.pageYOffset) >= (document.documentElement.scrollHeight - 4);
      var delta = e.deltaY * (e.deltaMode === 1 ? 16 : (e.deltaMode === 2 ? window.innerHeight : 1));
      var absDelta = Math.abs(delta);

      /* 向上：立即翻页，和以前一样 */
      if (delta < 0 && atTop) {
        e.preventDefault();
        wheelAccum = 0;
        wheelAt = 0;
        swap(idx - 1);
        return;
      }

      /* 向下到底：快速立即，慢速需要累积（方便点反馈） */
      if (!(delta > 0 && atBottom)) { wheelAccum = 0; wheelAt = 0; return; }
      e.preventDefault();
      if (absDelta >= 50) {
        wheelAccum = 0;
        wheelAt = 0;
        swap(idx + 1);
        return;
      }
      var now = Date.now();
      if (now - wheelAt > 400) { wheelAccum = 0; }
      wheelAt = now;
      wheelAccum += absDelta;
      if (wheelAccum >= 160) {
        wheelAccum = 0;
        wheelAt = 0;
        swap(idx + 1);
      }
    }, { passive: false });

    window.addEventListener('keydown', function (e) {
      if (animating || document.documentElement.classList.contains('feedback-open')) { return; }
      var atTop = window.pageYOffset <= 4;
      var atBottom = (window.innerHeight + window.pageYOffset) >= (document.documentElement.scrollHeight - 4);
      var nextKey = (e.key === 'ArrowDown' || e.key === 'PageDown');
      var prevKey = (e.key === 'ArrowUp' || e.key === 'PageUp');
      if (nextKey && atBottom) { e.preventDefault(); swap(idx + 1); }
      else if (prevKey && atTop) { e.preventDefault(); swap(idx - 1); }
    });

    var canScroll = function (node, dir) {
      var el = node;
      while (el && el !== document.body && el !== document.documentElement) {
        var style = window.getComputedStyle ? window.getComputedStyle(el) : null;
        var oy = style ? style.overflowY : '';
        if ((oy === 'auto' || oy === 'scroll') && el.scrollHeight > el.clientHeight + 1) {
          if (dir > 0 ? (el.scrollTop + el.clientHeight < el.scrollHeight - 1) : (el.scrollTop > 1)) { return true; }
        }
        el = el.parentElement;
      }
      return false;
    };

    var touchStartX = 0;
    var touchStartY = 0;
    var touchNode = null;
    var touching = false;

    window.addEventListener('touchstart', function (e) {
      if (animating || e.touches.length !== 1) { touching = false; return; }
      touching = true;
      touchStartX = e.touches[0].clientX;
      touchStartY = e.touches[0].clientY;
      touchNode = e.target;
    }, { passive: true });

    window.addEventListener('touchend', function (e) {
      if (!touching || animating) { return; }
      touching = false;
      var t = e.changedTouches && e.changedTouches[0];
      if (!t) { return; }
      var dx = t.clientX - touchStartX;
      var dy = t.clientY - touchStartY;
      if (Math.abs(dy) < 30 || Math.abs(dy) < Math.abs(dx) * 1.1) { return; }
      var atTop = window.pageYOffset <= touchSlack;
      var atBottom = (window.innerHeight + window.pageYOffset) >= (document.documentElement.scrollHeight - touchSlack);
      if (dy < 0) {
        if (atBottom && !canScroll(touchNode, 1)) { swap(idx + 1); }
      } else {
        if (atTop && !canScroll(touchNode, -1)) { swap(idx - 1); }
      }
    }, { passive: true });
    return { swap: swap, index: function () { return idx; }, pages: pages };
  }

  var agentQA = {
    zh: [
      { keys: ['贝贝', '小狗', '狗', '宠物'], a: '贝贝是我家的小狗，名字来自旺旺仙贝，活泼聪慧，最爱打滚' },
      { keys: ['二胡'], a: '二胡我学了十二年，最喜欢《三门峡畅想曲》，每次演出都很难忘' },
      { keys: ['篆刻', '刻章', '印章'], a: '我刻过很多章，欢迎大家找我刻章，一刀一刀雕出作品特别有成就感' },
      { keys: ['音乐', '歌手', 'coldplay', '听歌'], a: '最喜欢 Coldplay，心情不好会听 Welcome Home Son' },
      { keys: ['贵州菜', '粽子', '吃', '菜'], a: '啥都爱吃，最喜欢贵州菜；粽子必须是咸的，灰粽！' },
      { keys: ['脑机接口', '研究方向'], a: '我最感兴趣的是非侵入式脑机接口' },
      { keys: ['羽毛球'], a: '我喜欢看羽毛球比赛' },
      { keys: ['你是谁', '介绍一下', '自我介绍', '名字', '谁'], a: '我是何欣蔚，天津大学智能医学工程专业本科生' },
      { keys: ['学校', '专业', '天津大学', '学什么', '就读'], a: '我在天津大学读智能医学工程' },
      { keys: ['特长', '技能', '会什么', '二胡', '篆刻'], a: '我的特长是二胡和篆刻' },
      { keys: ['爱好', '兴趣', '喜欢什么', '音乐', '小狗', '狗'], a: '我喜欢探索新鲜事物，也喜欢音乐，还特别偏爱小狗' },
      { keys: ['项目', '作品', '做过什么'], a: '项目案例正在整理中，会陆续分享课程项目与设计探索' },
      { keys: ['联系', '邮箱', '邮件', '怎么找'], a: '可以发邮件到 xinwei_he@tju.edu.cn' },
      { keys: ['留言', '留言板'], a: '第三屏是留言板，欢迎留言' },
      { keys: ['你好', '您好', '嗨', '在吗'], a: '你好，我是何欣蔚的数字分身，问点你感兴趣的' }
    ],
    en: [
      { keys: ['dog', 'pet', 'beibei'], a: 'Beibei is my dog. Her name comes from a rice-cracker brand. She is lively and smart and loves rolling around' },
      { keys: ['erhu'], a: 'I have played the erhu for 12 years. My favourite piece is Sanmenxia Capriccio' },
      { keys: ['seal carving', 'seal', 'carving'], a: 'I have carved many seals and I am happy to carve one for you' },
      { keys: ['music', 'singer', 'coldplay'], a: 'My favourite band is Coldplay. When I feel down I listen to Welcome Home Son' },
      { keys: ['food', 'eat', 'guizhou'], a: 'I love all kinds of food, especially Guizhou cuisine. And zongzi must be savoury' },
      { keys: ['brain', 'bci', 'research'], a: 'My main interest is non-invasive brain-computer interfaces' },
      { keys: ['badminton'], a: 'I enjoy watching badminton matches' },
      { keys: ['who are you', 'your name', 'introduce', 'who'], a: 'I am He Xinwei, an undergraduate in Intelligent Medical Engineering at Tianjin University' },
      { keys: ['school', 'major', 'university', 'study'], a: 'I study Intelligent Medical Engineering at Tianjin University' },
      { keys: ['skill', 'specialty', 'erhu', 'seal'], a: 'My specialties are the erhu and seal carving' },
      { keys: ['hobby', 'interest', 'music', 'dog'], a: 'I like exploring new things and music, and I am especially fond of dogs' },
      { keys: ['project', 'work', 'portfolio'], a: 'Project cases are being organized and will be shared soon' },
      { keys: ['contact', 'email', 'reach'], a: 'You can email me at xinwei_he@tju.edu.cn' },
      { keys: ['message', 'board', 'comment'], a: 'The third screen has a message board' },
      { keys: ['hello', 'hey', 'hi there'], a: 'Hi, I am the digital twin of He Xinwei. Ask me what you like' }
    ]
  };

  function localAnswer(text) {
    var q = String(text || '').toLowerCase();
    var list = agentQA[current] || agentQA.zh;
    for (var i = 0; i < list.length; i++) {
      var item = list[i];
      for (var k = 0; k < item.keys.length; k++) {
        if (q.indexOf(item.keys[k].toLowerCase()) > -1) { return item.a; }
      }
    }
    return null;
  }

  var AGENT_ENDPOINT = SUPABASE_URL + '/functions/v1/ask-agent';

  function askModel(text) {
    return fetch(AGENT_ENDPOINT, {
      method: 'POST',
      headers: {
        apikey: SUPABASE_KEY,
        Authorization: 'Bearer ' + SUPABASE_KEY,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ question: String(text).slice(0, 200), lang: current })
    }).then(function (res) {
      if (res.status === 429) { throw new Error('rate'); }
      if (!res.ok) { throw new Error('HTTP ' + res.status); }
      return res.json();
    }).then(function (data) {
      if (!data || !data.answer) { throw new Error('empty'); }
      return String(data.answer).trim();
    });
  }

  var agentGreeting = null;

  function initAgent(pager) {
    var log = document.getElementById('chatLog');
    var form = document.getElementById('chatForm');
    var input = document.getElementById('chatInput');
    var quick = document.getElementById('chatQuick');
    var ball = document.getElementById('agentBall');
    if (!log) { return; }

    var index4 = -1;
    if (pager && pager.pages) {
      for (var i = 0; i < pager.pages.length; i++) {
        if (pager.pages[i].id === 'page4') { index4 = i; }
      }
    }

    if (ball && pager && index4 > -1) {
      ball.addEventListener('click', function () { pager.swap(index4); });
    }

    var addBubble = function (text, who) {
      var li = document.createElement('li');
      li.className = 'chat-item ' + (who === 'me' ? 'chat-me' : 'chat-bot');
      var bubble = document.createElement('div');
      bubble.className = 'chat-bubble';
      bubble.textContent = text;
      li.appendChild(bubble);
      log.appendChild(li);
      log.scrollTop = log.scrollHeight;
      return bubble;
    };

    var typeOut = function (bubble, text) {
      if (reduceMotion) { bubble.textContent = text; return; }
      var i = 0;
      bubble.textContent = '';
      var timer = window.setInterval(function () {
        i += 1;
        bubble.textContent = text.slice(0, i);
        log.scrollTop = log.scrollHeight;
        if (i >= text.length) { window.clearInterval(timer); }
      }, 28);
    };

    var respond = function (text) {
      var bubble = addBubble('···', 'bot');
      bubble.classList.add('chat-typing');

      var local = localAnswer(text);
      if (local) {
        window.setTimeout(function () {
          bubble.classList.remove('chat-typing');
          typeOut(bubble, local);
        }, reduceMotion ? 0 : 400);
        return;
      }

      var finished = false;
      var guard = null;
      var show = function (answer) {
        if (finished) { return; }
        finished = true;
        if (guard) { window.clearTimeout(guard); }
        bubble.classList.remove('chat-typing');
        typeOut(bubble, answer);
      };
      guard = window.setTimeout(function () { show(t('agentOffline')); }, 30000);

      askModel(text).then(function (answer) {
        show(answer);
      }).catch(function (err) {
        if (err && err.message === 'rate') { show(t('agentLimit')); }
        else { show(t('agentOffline')); }
      });
    };

    var send = function (text) {
      var value = String(text || '').trim();
      if (!value) { return; }
      addBubble(value, 'me');
      respond(value);
      if (input) { input.value = ''; }
    };

    if (form) {
      form.addEventListener('submit', function (e) {
        e.preventDefault();
        send(input ? input.value : '');
      });
    }

    if (quick) {
      quick.addEventListener('click', function (e) {
        var btn = e.target.closest ? e.target.closest('.chip') : null;
        if (!btn) { return; }
        var key = btn.getAttribute('data-i18n');
        if (key) { send(t(key)); }
      });
    }

    agentGreeting = addBubble(t('agentHello'), 'bot');
  }
  function submitFeedback(data) {
    return apiFetch('feedback', {
      method: 'POST',
      prefer: 'return=minimal',
      body: {
        rating: data.score || null,
        device: data.device || deviceLabel(),
        content: data.text,
        contact: data.contact || null
      }
    });
  }
  function initFeedback() {
    var modal = document.getElementById('feedbackModal');
    var openBtn = document.getElementById('feedbackOpen');
    var closeBtn = document.getElementById('feedbackClose');
    var cancelBtn = document.getElementById('feedbackCancel');
    var form = document.getElementById('feedbackForm');
    var textArea = document.getElementById('feedbackText');
    var contact = document.getElementById('feedbackContact');
    var ratingRow = document.getElementById('ratingRow');
    var deviceRow = document.getElementById('deviceRow');
    if (!modal || !openBtn) { return; }

    var lastFocus = null;
    var score = 0;
    var device = '';

    var openModal = function () {
      lastFocus = document.activeElement;
      modal.removeAttribute('hidden');
      document.documentElement.classList.add('feedback-open');
      if (textArea) { textArea.focus(); }
    };
    var closeModal = function () {
      modal.setAttribute('hidden', '');
      document.documentElement.classList.remove('feedback-open');
      if (lastFocus && lastFocus.focus) { lastFocus.focus(); }
    };

    openBtn.addEventListener('click', openModal);
    if (closeBtn) { closeBtn.addEventListener('click', closeModal); }
    if (cancelBtn) { cancelBtn.addEventListener('click', closeModal); }
    modal.addEventListener('click', function (e) {
      if (e.target && e.target.getAttribute && e.target.getAttribute('data-close')) { closeModal(); }
    });
    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape' && !modal.hasAttribute('hidden')) { closeModal(); }
    });

    if (ratingRow) {
      ratingRow.addEventListener('click', function (e) {
        var btn = e.target.closest ? e.target.closest('.rating-dot') : null;
        if (!btn) { return; }
        var value = parseInt(btn.getAttribute('data-score'), 10) || 0;
        score = (score === value) ? 0 : value;
        var dots = ratingRow.querySelectorAll('.rating-dot');
        for (var i = 0; i < dots.length; i++) {
          dots[i].classList.toggle('is-on', i < score);
        }
      });
    }

    if (deviceRow) {
      deviceRow.addEventListener('click', function (e) {
        var chip = e.target.closest ? e.target.closest('.device-chip') : null;
        if (!chip) { return; }
        var value = chip.getAttribute('data-device') || '';
        device = (device === value) ? '' : value;
        var chips = deviceRow.querySelectorAll('.device-chip');
        for (var i = 0; i < chips.length; i++) {
          chips[i].classList.toggle('is-on', chips[i].getAttribute('data-device') === device);
        }
      });
    }

    if (form) {
      form.addEventListener('submit', function (e) {
        e.preventDefault();
        var submitBtn = form.querySelector('button[type="submit"]');
        var text = textArea ? textArea.value.trim() : '';
        if (!text) { showToast(t('feedbackEmpty'), 'error'); return; }
        if (submitBtn) { submitBtn.disabled = true; submitBtn.textContent = t('feedbackSending'); }
        submitFeedback({
          score: score,
          device: device,
          text: text,
          contact: contact ? contact.value.trim() : ''
        }).then(function () {
          showToast(t('feedbackSent'), 'success');
          form.reset();
          score = 0;
          device = '';
          if (deviceRow) {
            var chips2 = deviceRow.querySelectorAll('.device-chip');
            for (var d = 0; d < chips2.length; d++) { chips2[d].classList.remove('is-on'); }
          }
          if (ratingRow) {
            var dots2 = ratingRow.querySelectorAll('.rating-dot');
            for (var k = 0; k < dots2.length; k++) { dots2[k].classList.remove('is-on'); }
          }
          closeModal();
        }).catch(function () {
          showToast(t('feedbackError'), 'error');
        }).then(function () {
          if (submitBtn) { submitBtn.disabled = false; submitBtn.textContent = t('feedbackSubmit'); }
        });
      });
    }
  }
  function initCursor() {
    var finePointer = !!(window.matchMedia && window.matchMedia('(hover: hover) and (pointer: fine)').matches);
    if (!finePointer || reduceMotion) { return; }

    var ring = document.createElement('div');
    ring.className = 'cursor-ring';
    document.body.appendChild(ring);

    var x = window.innerWidth / 2;
    var y = window.innerHeight / 2;
    var rx = x;
    var ry = y;
    var pressed = false;
    var started = false;
    var running = false;

    var draw = function () {
      rx += (x - rx) * 0.16;
      ry += (y - ry) * 0.16;
      ring.style.transform = 'translate(' + rx + 'px,' + ry + 'px) scale(' + (pressed ? 0.9 : 1) + ')';
      if (Math.abs(x - rx) < 0.2 && Math.abs(y - ry) < 0.2) {
        rx = x;
        ry = y;
        running = false;
        return;
      }
      window.requestAnimationFrame(draw);
    };
    var start = function () {
      if (!running) {
        running = true;
        window.requestAnimationFrame(draw);
      }
    };

    window.addEventListener('pointermove', function (e) {
      if (e.pointerType === 'touch') { return; }
      x = e.clientX;
      y = e.clientY;
      start();
      if (!started) {
        started = true;
        rx = x;
        ry = y;
        document.documentElement.classList.add('cursor-on');
      }
    });
    window.addEventListener('pointerleave', function () {
      document.documentElement.classList.remove('cursor-on');
    });
    window.addEventListener('blur', function () {
      document.documentElement.classList.remove('cursor-on');
    });
    window.addEventListener('pointerdown', function () { pressed = true; start(); });
    window.addEventListener('pointerup', function () { pressed = false; start(); });

    document.addEventListener('pointerover', function (e) {
      var node = e.target;
      var textField = node && node.closest ? node.closest('input, textarea, [contenteditable="true"]') : null;
      var hit = node && node.closest ? node.closest('a, button, .chip, .avatar, .card, [role="option"]') : null;
      ring.classList.toggle('is-hover', !!hit);
      document.documentElement.classList.toggle('cursor-text', !!textField);
    });
  }
  var initial = detectLang();
  initBoard();
  initBoardLayout();
  applyLang(initial);
  initTheme();
  initPointerEffects();
  var pager = initPager();
  initAgent(pager);
  initFeedback();
  initAdmin();
  initCursor();

  var toggle = document.getElementById('langToggle');
  if (toggle) {
    toggle.addEventListener('click', function () {
      var next = current === 'zh' ? 'en' : 'zh';
      saveLang(next);
      applyLang(next);
    });
  }

  document.addEventListener('click', function (e) {
    var btn = e.target.closest ? e.target.closest('.btn') : null;
    if (!btn || btn.disabled) { return; }
    var rect = btn.getBoundingClientRect();
    var isKeyboard = !e.clientX && !e.clientY;
    var x = isKeyboard ? rect.left + rect.width / 2 : e.clientX;
    var y = isKeyboard ? rect.top + rect.height / 2 : e.clientY;
    addRipple(btn, x, y);
  });

  document.addEventListener('keydown', function (e) {
    if (e.key !== ' ' && e.key !== 'Spacebar') { return; }
    var btn = e.target.closest ? e.target.closest('.btn') : null;
    if (!btn || btn.tagName !== 'A') { return; }
    e.preventDefault();
    btn.click();
  });
})();